import { useCallback, useMemo, useState } from 'react';
import { FlatList, Pressable, Text, View, TextInput, StyleSheet, RefreshControl } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { supabase } from '../../lib/supabase';
import { Circle, loadCircles } from '../../lib/data';
import { coverTones, palette } from '../../lib/theme';
import { CircleCover, Eyebrow, Loading, Message, commonStyles as cs } from '../../components/ui';

export default function Discover() {
  const [rows, setRows] = useState<Circle[]>([]); const [query, setQuery] = useState(''); const [busy, setBusy] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(''); const [userId, setUserId] = useState<string | null>(null);
  const reload = useCallback(async (refresh = false) => { if (refresh) setRefreshing(true); else setBusy(true); setError(''); if (!supabase) { setError('Supabase is not configured. Add apps/mobile/.env to connect.'); setRows([]); setBusy(false); setRefreshing(false); return; } const { data: { user } } = await supabase.auth.getUser(); setUserId(user?.id ?? null); const result = await loadCircles(user?.id); setRows(result.data); setError(result.error); setBusy(false); setRefreshing(false); }, []);
  useFocusEffect(useCallback(() => { void reload(); }, [reload]));
  const filtered = useMemo(() => rows.filter(c => `${c.book_title} ${c.author}`.toLowerCase().includes(query.trim().toLowerCase())), [rows, query]);
  return <FlatList data={filtered} keyExtractor={c => c.id} style={cs.page} contentContainerStyle={cs.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void reload(true)} tintColor={palette.sageDark} />} ListHeaderComponent={<>
    <View style={s.top}><Text style={s.brand}>BOOKS <Text style={{ color: palette.sage }}>✳</Text> FRIENDS</Text><Pressable onPress={() => router.push('/sessions/create')} style={s.create}><Text style={s.createText}>＋ Start a circle</Text></Pressable></View>
    <Eyebrow>A SOFTER CORNER OF THE INTERNET</Eyebrow><Text style={s.hero}>Good books.{ '\n' }<Text style={s.italic}>Better together.</Text></Text><Text style={[cs.body, { marginTop: 4, marginBottom: 24 }]}>Find a book worth talking about, then find your people.</Text>
    <Text style={cs.section}>Reading circles</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search books or authors" placeholderTextColor="#9ba197" style={s.search} />
    {userId ? <Text style={s.small}>Welcome back to your reading life.</Text> : <Text style={s.small}>Browse freely. Join in whenever you’re ready.</Text>}
  </>} ListEmptyComponent={busy ? <Loading /> : <View style={s.empty}><Message error={Boolean(error)}>{error || 'No reading circles found yet.'}</Message>{!error && <Text style={cs.muted}>A good story is just around the corner.</Text>}</View>} renderItem={({ item, index }) => {
    const members = (item.session_members ?? []).filter(m => m.membership_status === 'active'); const progress = members.length ? Math.round(members.reduce((sum, m) => sum + m.current_chapter / item.total_chapters, 0) / members.length * 100) : 0;
    return <Pressable onPress={() => router.push(`/sessions/${item.id}`)} style={({ pressed }) => [cs.card, pressed && { opacity: .8 }]}><CircleCover title={item.book_title} author={item.author} color={coverTones[index % coverTones.length]} uri={item.cover_image_url} /><View style={{ padding: 15 }}><Text style={s.tag}>✳  READING TOGETHER{userId ? ` · ${members.length} READERS` : ''}</Text><Text style={s.book}>{item.book_title}</Text><Text style={s.author}>by {item.author}</Text><Text style={[cs.muted, { marginTop: 10 }]} numberOfLines={2}>{item.description || 'A shared read, and people to talk about it with.'}</Text>{userId && <><View style={s.track}><View style={[s.fill, { width: `${progress}%` }]} /></View><Text style={s.progress}>{progress}% group progress</Text></>}</View></Pressable>;
  }} />;
}
const s = StyleSheet.create({ top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 3, marginBottom: 29 }, brand: { color: palette.ink, fontSize: 11, letterSpacing: 2, fontWeight: '800' }, create: { backgroundColor: palette.ink, borderRadius: 7, paddingHorizontal: 11, paddingVertical: 9 }, createText: { color: 'white', fontSize: 11, fontWeight: '700' }, hero: { color: palette.ink, fontFamily: 'Georgia', fontSize: 40, lineHeight: 47, marginTop: 16, marginBottom: 12 }, italic: { color: palette.sage, fontStyle: 'italic' }, search: { backgroundColor: 'white', borderColor: palette.line, borderWidth: 1, borderRadius: 9, paddingHorizontal: 13, paddingVertical: 12, marginBottom: 8, color: palette.ink }, small: { color: '#92988f', fontSize: 11, marginBottom: 13 }, tag: { color: '#71816e', fontSize: 9, letterSpacing: .5 }, book: { color: palette.ink, fontFamily: 'Georgia', fontSize: 19, marginTop: 9 }, author: { color: '#849087', fontSize: 11, marginTop: 4 }, track: { backgroundColor: palette.soft, height: 5, borderRadius: 8, marginTop: 15 }, fill: { backgroundColor: '#84987d', height: 5, borderRadius: 8 }, progress: { color: '#8b9389', fontSize: 10, marginTop: 7 }, empty: { alignItems: 'center', padding: 25 } });
