import { useCallback, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { supabase } from '../../lib/supabase';
import { palette } from '../../lib/theme';
import { Button, Eyebrow, Loading, Message, Page, Title, commonStyles as cs } from '../../components/ui';
type Row = { current_chapter: number; progress_note: string | null; reading_sessions: { id: string; book_title: string; author: string; total_chapters: number; status: string } | null };
export default function MyReading() { const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [signedIn, setSignedIn] = useState(false); const [error, setError] = useState(''); const load = useCallback(async () => { setLoading(true); if (!supabase) { setError('Supabase is not configured.'); setLoading(false); return; } const { data: { user } } = await supabase.auth.getUser(); setSignedIn(Boolean(user)); if (!user) { setRows([]); setLoading(false); return; } const { data, error: e } = await supabase.from('session_members').select('current_chapter,progress_note,reading_sessions(id,book_title,author,total_chapters,status)').eq('user_id', user.id).eq('membership_status', 'active').order('joined_at', { ascending: false }); setRows((data ?? []) as unknown as Row[]); if (e) setError(e.message); setLoading(false); }, []); useFocusEffect(useCallback(() => { void load(); }, [load]));
 return <Page><FlatList data={rows} keyExtractor={r => r.reading_sessions?.id ?? Math.random().toString()} contentContainerStyle={s.content} ListHeaderComponent={<><Eyebrow>YOUR READING LIFE</Eyebrow><Title>My reading.</Title><Text style={[cs.body, { marginBottom: 22 }]}>All the circles you’re part of, gathered in one place.</Text></>} ListEmptyComponent={loading ? <Loading /> : <View style={s.empty}><Text style={s.icon}>▤</Text><Text style={s.emptyTitle}>{error || (signedIn ? 'Your next read is out there.' : 'Your reading shelf is waiting.')}</Text><Text style={[cs.muted, { textAlign: 'center', marginTop: 6 }]}>{signedIn ? 'Join a circle to keep your reading together.' : 'Sign in to see the circles you’ve joined.'}</Text>{!signedIn && <Button title="Sign in" onPress={() => router.push('/auth')} />}<Button title="Explore reading circles" light onPress={() => router.replace('/(tabs)')} /></View>} renderItem={({ item }) => { const book = item.reading_sessions; if (!book) return null; const pct = Math.round(item.current_chapter / book.total_chapters * 100); return <Pressable onPress={() => router.push(`/sessions/${book.id}`)} style={[cs.card, s.card]}><Text style={s.title}>{book.book_title}</Text><Text style={cs.muted}>by {book.author}</Text><View style={s.track}><View style={[s.fill, { width: `${pct}%` }]} /></View><View style={cs.spread}><Text style={s.chapter}>Chapter {item.current_chapter} of {book.total_chapters}</Text><Text style={s.chapter}>{pct}%</Text></View>{item.progress_note ? <Text style={s.note} numberOfLines={2}>“{item.progress_note}”</Text> : null}</Pressable> }} /></Page>;
}
const s = StyleSheet.create({ content: { padding: 22, paddingTop: 27, paddingBottom: 35 }, empty: { alignItems: 'center', padding: 26 }, icon: { color: palette.sage, fontSize: 29, marginBottom: 11 }, emptyTitle: { color: palette.ink, fontFamily: 'Georgia', fontSize: 20, textAlign: 'center' }, card: { padding: 16 }, title: { color: palette.ink, fontFamily: 'Georgia', fontSize: 19, marginBottom: 5 }, track: { height: 5, borderRadius: 8, backgroundColor: palette.soft, marginTop: 18 }, fill: { height: 5, borderRadius: 8, backgroundColor: palette.sage }, chapter: { color: '#849087', fontSize: 11, marginTop: 8 }, note: { borderTopWidth: 1, borderTopColor: palette.line, paddingTop: 12, marginTop: 12, color: palette.muted, fontSize: 12, fontStyle: 'italic' } });
