import { useCallback, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { supabase } from '../../lib/supabase';
import { palette } from '../../lib/theme';
import { Button, Eyebrow, Loading, Page, Title, commonStyles as cs } from '../../components/ui';
type Notice = { id: string; notification_type: string; is_read: boolean; created_at: string; session_id: string | null; actor: { display_name: string } | null; session: { book_title: string } | null };
export default function Notifications() { const [items, setItems] = useState<Notice[]>([]); const [loading, setLoading] = useState(true); const [signedIn, setSignedIn] = useState(false); const [error, setError] = useState(''); const load = useCallback(async () => { setLoading(true); if (!supabase) { setError('Supabase is not configured.'); setLoading(false); return; } const { data: { user } } = await supabase.auth.getUser(); setSignedIn(Boolean(user)); if (!user) { setItems([]); setLoading(false); return; } const { data, error: e } = await supabase.from('notifications').select('id,notification_type,is_read,created_at,session_id,actor:profiles!notifications_actor_id_fkey(display_name),session:reading_sessions!notifications_session_id_fkey(book_title)').order('created_at', { ascending: false }).limit(50); if (e) setError(e.message); setItems((data ?? []) as unknown as Notice[]); setLoading(false); }, []); useFocusEffect(useCallback(() => { void load(); }, [load]));
 async function markRead(item: Notice) { if (!supabase || item.is_read) return; await supabase.from('notifications').update({ is_read: true }).eq('id', item.id); setItems(list => list.map(n => n.id === item.id ? { ...n, is_read: true } : n)); }
 async function markAll() { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { error: e } = await supabase.from('notifications').update({ is_read: true }).eq('recipient_id', user.id).eq('is_read', false); if (e) setError(e.message); else setItems(list => list.map(n => ({ ...n, is_read: true }))); }
 return <Page><FlatList data={items} keyExtractor={n => n.id} contentContainerStyle={s.content} ListHeaderComponent={<View style={{ marginBottom: 12 }}><Eyebrow>LITTLE NOTES FROM YOUR CIRCLES</Eyebrow><View style={cs.spread}><Title>Notifications.</Title>{signedIn && !!items.length && <Pressable onPress={() => void markAll()}><Text style={s.link}>Mark all read</Text></Pressable>}</View></View>} ListEmptyComponent={loading ? <Loading /> : <View style={s.empty}><Text style={s.icon}>♡</Text><Text style={s.emptyTitle}>{error || (signedIn ? 'All caught up.' : 'A little something, when you join.')}</Text><Text style={[cs.muted, { textAlign: 'center', marginTop: 7 }]}>{signedIn ? 'When something happens in your circles, you’ll find it here.' : 'Sign in to see updates from your circles.'}</Text>{!signedIn && <Button title="Sign in" onPress={() => router.push('/auth')} />}</View>} renderItem={({ item }) => <Pressable onPress={() => { void markRead(item); if (item.session_id) router.push(`/sessions/${item.session_id}`); }} style={[s.row, !item.is_read && s.unread]}><View style={s.bell}><Text style={s.iconSmall}>♡</Text></View><View style={{ flex: 1 }}><Text style={s.copy}>{noticeText(item)}</Text><Text style={s.date}>{new Date(item.created_at).toLocaleDateString()}</Text></View></Pressable>} /></Page>;
}
function noticeText(n: Notice) { const name = n.actor?.display_name ?? 'A reader'; const book = n.session?.book_title ?? 'your reading circle'; if (n.notification_type === 'comment') return `${name} added a note in ${book}.`; if (n.notification_type === 'reaction') return `${name} reacted to a reading note in ${book}.`; if (n.notification_type === 'member_joined') return `${name} joined ${book}.`; return `There’s an update in ${book}.`; }
const s = StyleSheet.create({ content: { padding: 22, paddingTop: 27, paddingBottom: 35 }, empty: { alignItems: 'center', padding: 26 }, icon: { color: palette.sage, fontSize: 30 }, emptyTitle: { color: palette.ink, fontFamily: 'Georgia', fontSize: 20, textAlign: 'center', marginTop: 8 }, row: { backgroundColor: 'white', borderRadius: 10, borderColor: palette.line, borderWidth: 1, padding: 14, flexDirection: 'row', gap: 12, marginBottom: 10 }, unread: { backgroundColor: '#f2f4ee', borderColor: '#d7e0d2' }, bell: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#eaf0e6' }, iconSmall: { color: palette.sageDark, fontSize: 17 }, copy: { color: palette.ink, fontSize: 12, lineHeight: 18 }, date: { color: '#92988f', fontSize: 10, marginTop: 5 }, link: { color: palette.sageDark, fontSize: 11, fontWeight: '700', marginTop: 20 } });
