import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { supabase } from '../../lib/supabase';
import { palette } from '../../lib/theme';
import { Avatar, Button, Eyebrow, Field, Loading, Message, Page, Title, commonStyles as cs } from '../../components/ui';

const MAX_SIZE = 2 * 1024 * 1024;
const MIME_EXT: Record<string, string> = { 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp' };
export default function Profile() {
 const [id, setId] = useState(''); const [name, setName] = useState(''); const [bio, setBio] = useState(''); const [avatar, setAvatar] = useState<string | null>(null); const [email, setEmail] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [error, setError] = useState('');
 const load = useCallback(async () => { if (!supabase) { setLoading(false); setError('Supabase is not configured.'); return; } setLoading(true); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setId(''); setLoading(false); return; } setId(user.id); setEmail(user.email ?? ''); const { data, error: e } = await supabase.from('profiles').select('display_name,bio,avatar_url').eq('id', user.id).single(); if (e) setError(e.message); else { setName(data.display_name ?? ''); setBio(data.bio ?? ''); setAvatar(data.avatar_url); } setLoading(false); }, []);
 useFocusEffect(useCallback(() => { void load(); }, [load]));
 async function save() { if (!supabase || !id) return; if (!name.trim()) { setError('Please enter a display name.'); return; } setBusy(true); setError(''); setMessage(''); const { error: e } = await supabase.from('profiles').update({ display_name: name.trim(), bio: bio.trim() || null }).eq('id', id); if (e) setError(e.message); else setMessage('Your profile has been saved.'); setBusy(false); }
 async function choosePhoto() { if (!supabase || !id) return; const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setError('Allow photo library access to choose a profile photo.'); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [1, 1], quality: .85 }); if (result.canceled) return; const image = result.assets[0]; const mime = image.mimeType ?? 'image/jpeg'; if (!MIME_EXT[mime]) { setError('Choose a JPEG, PNG, or WebP image.'); return; } if (image.fileSize && image.fileSize > MAX_SIZE) { setError('Choose an image smaller than 2 MB.'); return; } setBusy(true); setError(''); setMessage(''); try { const response = await fetch(image.uri); const body = await response.arrayBuffer(); if (body.byteLength > MAX_SIZE) throw new Error('Choose an image smaller than 2 MB.'); const path = `${id}/${Date.now()}-${Math.random().toString(36).slice(2)}.${MIME_EXT[mime]}`; const { error: uploadError } = await supabase.storage.from('avatars').upload(path, body, { contentType: mime, upsert: false }); if (uploadError) throw uploadError; const { data: publicUrl } = supabase.storage.from('avatars').getPublicUrl(path); const { error: updateError } = await supabase.from('profiles').update({ avatar_url: publicUrl.publicUrl }).eq('id', id); if (updateError) { await supabase.storage.from('avatars').remove([path]); throw updateError; } setAvatar(publicUrl.publicUrl); setMessage('Your profile photo has been updated.'); } catch (e) { setError(e instanceof Error ? e.message : 'The photo could not be uploaded.'); } finally { setBusy(false); } }
 async function removePhoto() { if (!supabase || !id || !avatar) return; setBusy(true); const old = avatar; const { error: e } = await supabase.from('profiles').update({ avatar_url: null }).eq('id', id); if (e) setError(e.message); else { setAvatar(null); setMessage('Your profile photo was removed.'); const path = getAvatarPath(old); if (path?.startsWith(`${id}/`)) await supabase.storage.from('avatars').remove([path]); } setBusy(false); }
 async function signOut() { if (!supabase) return; const { error: e } = await supabase.auth.signOut(); if (e) setError(e.message); else { setId(''); setName(''); setAvatar(null); setMessage('You’re signed out.'); } }
 if (loading) return <Page><Loading /></Page>;
 if (!id) return <Page><ScrollView contentContainerStyle={s.content}><Eyebrow>YOUR PLACE IN THE CIRCLE</Eyebrow><Title>Read together.</Title><Text style={cs.body}>Sign in to keep your reading life close, follow your circles, and join the conversation.</Text><Button title="Sign in" onPress={() => router.push('/auth')} /><Button title="Create an account" light onPress={() => router.push('/auth?mode=sign-up')} /></ScrollView></Page>;
 return <Page><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Eyebrow>YOUR PLACE IN THE CIRCLE</Eyebrow><Title>Profile settings.</Title><Text style={s.copy}>A familiar face makes every reading circle feel a little closer.</Text><View style={s.avatarRow}><Avatar name={name} uri={avatar} size={76} /><View style={{ flex: 1 }}><Text style={s.heading}>Your profile photo</Text><Text style={cs.muted}>JPEG, PNG, or WebP · up to 2 MB</Text><Pressable disabled={busy} onPress={() => void choosePhoto()}><Text style={s.link}>{busy ? 'Working…' : avatar ? 'Change photo' : 'Upload photo'}</Text></Pressable>{avatar && <Pressable onPress={() => Alert.alert('Remove profile photo?', 'Your photo will be removed from your profile.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => void removePhoto() }])}><Text style={s.remove}>Remove photo</Text></Pressable>}</View></View><Text style={s.label}>Display name</Text><Field value={name} onChangeText={setName} maxLength={60} /><Text style={s.label}>About you</Text><Field value={bio} onChangeText={setBio} multiline maxLength={500} placeholder="A little about the books you love…" style={{ minHeight: 90, textAlignVertical: 'top' }} /><Text style={s.email}>{email}</Text><Message error={Boolean(error)}>{error}</Message><Message>{message}</Message><Button title={busy ? 'Saving…' : 'Save profile'} disabled={busy} onPress={() => void save()} /><View style={s.divider} /><Text style={s.heading}>Account</Text><Pressable onPress={() => router.push('/sessions/create')}><Text style={s.link}>＋ Start a reading circle</Text></Pressable><Pressable onPress={() => void signOut()}><Text style={s.signout}>Sign out</Text></Pressable></ScrollView></Page>;
}
function getAvatarPath(url: string) { try { const p = new URL(url).pathname; const marker = '/storage/v1/object/public/avatars/'; const i = p.indexOf(marker); return i < 0 ? null : decodeURIComponent(p.slice(i + marker.length)); } catch { return null; } }
const s = StyleSheet.create({ content: { padding: 22, paddingTop: 26, paddingBottom: 50 }, copy: { color: palette.muted, lineHeight: 21, marginBottom: 22 }, avatarRow: { flexDirection: 'row', gap: 15, alignItems: 'center', backgroundColor: '#f4f4ee', borderRadius: 12, padding: 15, marginBottom: 22 }, heading: { color: palette.ink, fontSize: 13, fontWeight: '700', marginBottom: 5 }, link: { color: palette.sageDark, fontSize: 12, fontWeight: '700', marginTop: 10 }, remove: { color: '#a54f41', fontSize: 12, marginTop: 7 }, label: { color: palette.ink, fontSize: 12, fontWeight: '600' }, email: { color: '#92988f', fontSize: 12, marginTop: 6 }, divider: { height: 1, backgroundColor: palette.line, marginVertical: 23 }, signout: { color: '#a54f41', fontSize: 13, fontWeight: '700', marginTop: 22 } });
