import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { supabase } from '../../lib/supabase';
import { Circle, Comment, loadComments } from '../../lib/data';
import { coverTones, palette } from '../../lib/theme';
import { Avatar, Button, CircleCover, Eyebrow, Field, Loading, Message, Page, commonStyles as cs } from '../../components/ui';

const emojis = ['❤️', '👍', '😂', '🔥', '👏'];
export default function SessionDetail() {
 const { id } = useLocalSearchParams<{ id: string }>(); const [circle, setCircle] = useState<Circle | null>(null); const [comments, setComments] = useState<Comment[]>([]); const [userId, setUserId] = useState(''); const [member, setMember] = useState(false); const [chapter, setChapter] = useState('0'); const [note, setNote] = useState(''); const [draft, setDraft] = useState(''); const [reference, setReference] = useState(''); const [editingId, setEditingId] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
 const reloadComments = useCallback(async () => { if (id) setComments(await loadComments(id)); }, [id]);
 const load = useCallback(async () => { if (!id || !supabase) { setLoading(false); if (!supabase) setError('Supabase is not configured.'); return; } setLoading(true); setError(''); const { data: { user } } = await supabase.auth.getUser(); setUserId(user?.id ?? ''); const select = `id,book_title,author,total_chapters,description,cover_image_url,status,creator_id,profiles!reading_sessions_creator_id_fkey(display_name,avatar_url)${user ? ',session_members(id,user_id,current_chapter,progress_note,membership_status,profiles(display_name,avatar_url))' : ''}`; const [{ data, error: e }, cs] = await Promise.all([supabase.from('reading_sessions').select(select).eq('id', id).single(), loadComments(id)]); if (e) setError(e.message); else setCircle(data as unknown as Circle); setComments(cs); if (user) { const { data: own } = await supabase.from('session_members').select('id,current_chapter,progress_note,membership_status').eq('session_id', id).eq('user_id', user.id).maybeSingle(); const active = own?.membership_status === 'active'; setMember(active); if (active) { setChapter(String(own.current_chapter)); setNote(own.progress_note ?? ''); } } else { setMember(false); } setLoading(false); }, [id]);
 useEffect(() => { void load(); }, [load]);
 useEffect(() => { const client = supabase; if (!id || !client) return; const ch = client.channel(`mobile-circle-${id}`).on('postgres_changes', { event: '*', schema: 'public', table: 'comments', filter: `session_id=eq.${id}` }, () => { void reloadComments(); }); if (userId) ch.on('postgres_changes', { event: '*', schema: 'public', table: 'session_members', filter: `session_id=eq.${id}` }, () => { void load(); }); ch.subscribe(); return () => { void client.removeChannel(ch); }; }, [id, userId, reloadComments, load]);
 useEffect(() => { const client = supabase; if (!client || !comments.length) return; const channel = client.channel(`mobile-reactions-${comments.map(c => c.id).join('-')}`); comments.forEach(c => channel.on('postgres_changes', { event: '*', schema: 'public', table: 'reactions', filter: `comment_id=eq.${c.id}` }, () => { void reloadComments(); })); channel.subscribe(); return () => { void client.removeChannel(channel); }; }, [comments.map(c => c.id).join(','), reloadComments]);
 const members = useMemo(() => (circle?.session_members ?? []).filter(m => m.membership_status === 'active'), [circle]); const groupProgress = members.length && circle ? Math.round(members.reduce((sum, m) => sum + m.current_chapter / circle.total_chapters, 0) / members.length * 100) : 0;
 async function join() { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) { router.push('/auth'); return; } setBusy(true); const { error: e } = await supabase.from('session_members').upsert({ session_id: id, user_id: user.id, membership_status: 'active' }, { onConflict: 'session_id,user_id' }); if (e) setError(e.message); else { setUserId(user.id); await load(); setMessage('You’ve joined the circle.'); } setBusy(false); }
 async function saveProgress() { if (!supabase || !userId || Number(chapter) < 0 || Number(chapter) > (circle?.total_chapters ?? 0)) { setError('Enter a chapter within this book’s range.'); return; } setBusy(true); const { error: e } = await supabase.from('session_members').update({ current_chapter: Number(chapter), progress_note: note.trim() || null, last_progress_at: new Date().toISOString() }).eq('session_id', id).eq('user_id', userId); if (e) setError(e.message); else { setMessage('Your reading progress is saved.'); await load(); } setBusy(false); }
 async function postComment() { if (!supabase || !userId || !draft.trim()) return; setBusy(true); setError(''); const fields = { content: draft.trim(), chapter_reference: reference.trim() ? Number(reference) : null }; const result = editingId ? await supabase.from('comments').update(fields).eq('id', editingId).eq('user_id', userId) : await supabase.from('comments').insert({ ...fields, session_id: id, user_id: userId }); if (result.error) setError(result.error.message); else { setDraft(''); setReference(''); setEditingId(''); setMessage(editingId ? 'Your note was updated.' : 'Your note was posted.'); await reloadComments(); } setBusy(false); }
 function editComment(comment: Comment) { setEditingId(comment.id); setDraft(comment.content); setReference(comment.chapter_reference ? String(comment.chapter_reference) : ''); setMessage('Editing your reading note.'); }
 function deleteComment(comment: Comment) { if (!supabase) return; Alert.alert('Delete this reading note?', 'This note and its reactions will be removed.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { const client = supabase; if (!client) return; const { error: e } = await client.from('comments').delete().eq('id', comment.id).eq('user_id', userId); if (e) setError(e.message); else { setMessage('Your note was deleted.'); await reloadComments(); } } }]); }
 async function toggleReaction(comment: Comment, emoji: string) { if (!supabase) return; if (!userId) { router.push('/auth'); return; } if (!member) { setMessage('Join this circle to react to reading notes.'); return; } const mine = comment.reactions.find(r => r.user_id === userId); const result = mine ? (mine.emoji === emoji ? await supabase.from('reactions').delete().eq('id', mine.id) : await supabase.from('reactions').update({ emoji }).eq('id', mine.id)) : await supabase.from('reactions').insert({ comment_id: comment.id, user_id: userId, emoji }); if (result.error) setError(result.error.message); else await reloadComments(); }
 if (loading) return <Page><Loading /></Page>;
 if (!circle) return <Page><View style={s.error}><Message error>{error || 'This reading circle could not be found.'}</Message><Button title="Back to discover" onPress={() => router.replace('/(tabs)')} /></View></Page>;
 const activeMembers = members;
 return <Page><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><FlatList data={comments} keyExtractor={c => c.id} keyboardShouldPersistTaps="handled" contentContainerStyle={s.content} ListHeaderComponent={<>
    <Pressable onPress={() => router.back()}><Text style={s.back}>‹  All reading circles</Text></Pressable><View style={cs.card}><CircleCover title={circle.book_title} author={circle.author} color={coverTones[0]} uri={circle.cover_image_url} /><View style={{ padding: 17 }}><Eyebrow>A BOOK IN GOOD COMPANY</Eyebrow><Text style={s.bookTitle}>{circle.book_title}</Text><Text style={s.byline}>by {circle.author}</Text><Text style={[cs.body, { marginTop: 14 }]}>{circle.description || `A shared read, hosted by ${circle.profiles?.display_name ?? 'a reader'}.`}</Text><View style={s.stats}><Text style={s.stat}>▤  {circle.total_chapters} chapters</Text>{userId && <><Text style={s.stat}>◉  {activeMembers.length} readers</Text><Text style={s.stat}>{groupProgress}% together</Text></>}</View>{!member && circle.status === 'active' && <Button title={busy ? 'Joining…' : 'Join this circle  ↗'} disabled={busy} onPress={() => void join()} />}</View></View>
    {userId && <View style={s.panel}><Eyebrow>YOUR CIRCLE, PAGE BY PAGE</Eyebrow><View style={cs.spread}><Text style={s.section}>Readers’ progress.</Text><Text style={cs.muted}>{activeMembers.length} readers</Text></View>{activeMembers.length ? activeMembers.map((m, i) => { const pct = Math.round(m.current_chapter / circle.total_chapters * 100); const isYou = m.user_id === userId; return <View key={m.id || m.user_id} style={s.reader}><View style={cs.spread}><View style={[cs.row, { gap: 8 }]}><Avatar name={m.profiles?.display_name} uri={m.profiles?.avatar_url} size={32} /><Text style={s.readerName}>{m.profiles?.display_name ?? 'Reader'}</Text>{isYou && <Text style={s.you}>YOU</Text>}</View><Text style={s.readerChapter}>Ch. {m.current_chapter} / {circle.total_chapters} · {pct}%</Text></View><View style={s.track}><View style={[s.fill, { width: `${pct}%` }]} /></View></View>; }) : <Text style={cs.muted}>No one has joined this circle yet.</Text>}</View>}
    {member && <View style={s.panel}><Eyebrow>KEEP YOUR PLACE</Eyebrow><Text style={s.section}>Your reading.</Text><Text style={s.label}>Current chapter</Text><Field value={chapter} onChangeText={setChapter} keyboardType="number-pad" /><Text style={s.label}>A note (optional)</Text><Field value={note} onChangeText={setNote} maxLength={300} placeholder="A thought to remember…" /><Button title={busy ? 'Saving…' : 'Save progress'} disabled={busy} onPress={() => void saveProgress()} /></View>}
    <View style={s.discussion}><Eyebrow>THE CONVERSATION</Eyebrow><View style={cs.spread}><Text style={s.section}>Reading notes.</Text><Text style={cs.muted}>♡  {comments.length}</Text></View><Text style={[cs.muted, { marginBottom: 10 }]}>Comments are open to everyone. Join this circle to add a note.</Text></View>
  </>} ListEmptyComponent={<View style={s.empty}><Text style={[cs.muted, { textAlign: 'center' }]}>A quiet page, so far. Be the first to leave a note.</Text></View>} renderItem={({ item }) => <CommentCard comment={item} userId={userId} onEdit={() => editComment(item)} onDelete={() => deleteComment(item)} onReact={(emoji) => void toggleReaction(item, emoji)} />}
  ListFooterComponent={<>{(editingId || (member && circle.status === 'active')) && <View style={s.compose}><Text style={s.composeTitle}>{editingId ? 'Edit your note' : 'Add a reading note'}</Text><Field value={draft} onChangeText={setDraft} multiline maxLength={2000} placeholder="Share a thought from your reading…" style={{ minHeight: 70, textAlignVertical: 'top' }} /><Field value={reference} onChangeText={setReference} keyboardType="number-pad" placeholder="Chapter reference (optional)" />{reference && (Number(reference) < 1 || Number(reference) > circle.total_chapters) ? <Message error>Chapter must be between 1 and {circle.total_chapters}.</Message> : null}<Button title={busy ? 'Saving…' : editingId ? 'Save changes' : 'Post reading note  ↗'} disabled={busy || !draft.trim() || (!!reference && (Number(reference) < 1 || Number(reference) > circle.total_chapters))} onPress={() => void postComment()} />{editingId ? <Pressable onPress={() => { setEditingId(''); setDraft(''); setReference(''); }}><Text style={s.cancel}>Cancel editing</Text></Pressable> : null}</View>}{error ? <Message error>{error}</Message> : null}{message ? <Message>{message}</Message> : null}</>}
 /></KeyboardAvoidingView></Page>;
}
function CommentCard({ comment, userId, onEdit, onDelete, onReact }: { comment: Comment; userId: string; onEdit: () => void; onDelete: () => void; onReact: (emoji: string) => void }) { return <View style={s.comment}><Avatar name={comment.profiles?.display_name} uri={comment.profiles?.avatar_url} size={34} /><View style={{ flex: 1 }}><View style={cs.row}><Text style={s.commentName}>{comment.profiles?.display_name ?? 'Reader'}</Text>{comment.chapter_reference ? <Text style={s.chapterTag}>Chapter {comment.chapter_reference}</Text> : null}</View><Text style={s.commentBody}>{comment.content}</Text><Text style={s.date}>{new Date(comment.created_at).toLocaleDateString()}</Text>{userId === comment.user_id && <View style={s.ownActions}><Pressable onPress={onEdit}><Text style={s.action}>Edit note</Text></Pressable><Pressable onPress={onDelete}><Text style={[s.action, { color: '#a54f41' }]}>Delete</Text></Pressable></View>}<View style={s.reactions}>{emojis.map(emoji => { const matches = comment.reactions.filter(r => r.emoji === emoji); const mine = matches.some(r => r.user_id === userId); return <Pressable key={emoji} onPress={() => onReact(emoji)} style={[s.reaction, mine && s.reactionMine]}><Text style={{ fontSize: 13 }}>{emoji}</Text>{matches.length > 0 && <Text style={s.count}>{matches.length}</Text>}</Pressable>; })}</View>{comment.reactions.length > 0 && <Text style={s.names}>{Array.from(new Set(comment.reactions.map(r => r.profiles?.display_name).filter(Boolean))).join(', ')} reacted</Text>}</View></View>; }
const s = StyleSheet.create({ content: { padding: 17, paddingBottom: 40 }, back: { color: palette.sageDark, fontSize: 13, marginVertical: 8 }, bookTitle: { color: palette.ink, fontFamily: 'Georgia', fontSize: 26, marginTop: 10 }, byline: { color: '#849087', fontSize: 12, marginTop: 5 }, stats: { flexDirection: 'row', flexWrap: 'wrap', gap: 13, marginTop: 16, marginBottom: 5 }, stat: { color: palette.sageDark, fontSize: 11 }, panel: { borderWidth: 1, borderColor: '#e7eadf', backgroundColor: '#f6f7f1', borderRadius: 12, padding: 15, marginBottom: 15 }, section: { fontFamily: 'Georgia', color: palette.ink, fontSize: 21, marginVertical: 9 }, reader: { paddingVertical: 10, borderTopWidth: 1, borderTopColor: '#e8eadf' }, readerName: { color: palette.ink, fontSize: 12, fontWeight: '600' }, you: { color: palette.sageDark, backgroundColor: '#e5ecdf', paddingHorizontal: 6, paddingVertical: 3, borderRadius: 8, fontSize: 8, fontWeight: '800' }, readerChapter: { color: palette.muted, fontSize: 10 }, track: { height: 5, backgroundColor: '#e6eade', borderRadius: 6, marginTop: 8 }, fill: { height: 5, backgroundColor: '#84987d', borderRadius: 6 }, label: { color: palette.ink, fontSize: 12, fontWeight: '600' }, discussion: { marginTop: 8 }, empty: { borderWidth: 1, borderColor: palette.line, borderStyle: 'dashed', borderRadius: 10, padding: 18, marginVertical: 10 }, comment: { flexDirection: 'row', gap: 10, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: palette.line }, commentName: { color: palette.ink, fontSize: 12, fontWeight: '700', marginRight: 8 }, chapterTag: { color: palette.sageDark, backgroundColor: '#eff2eb', paddingHorizontal: 7, paddingVertical: 3, borderRadius: 7, fontSize: 9 }, commentBody: { color: '#536057', fontSize: 13, lineHeight: 19, marginTop: 7 }, date: { color: '#9ba197', fontSize: 9, marginTop: 7 }, reactions: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 9 }, ownActions: { flexDirection: 'row', gap: 15, marginTop: 9 }, action: { color: palette.sageDark, fontSize: 11, fontWeight: '700' }, reaction: { borderWidth: 1, borderColor: palette.line, backgroundColor: 'white', borderRadius: 15, paddingVertical: 4, paddingHorizontal: 7, flexDirection: 'row', alignItems: 'center', gap: 4 }, reactionMine: { borderColor: '#9aaf91', backgroundColor: '#eff4ea' }, count: { color: palette.sageDark, fontSize: 10 }, names: { color: '#849087', fontSize: 9, marginTop: 6 }, compose: { borderTopWidth: 1, borderTopColor: palette.line, marginTop: 13, paddingTop: 13 }, composeTitle: { color: palette.ink, fontFamily: 'Georgia', fontSize: 18, marginBottom: 5 }, cancel: { color: palette.sageDark, textAlign: 'center', marginTop: 13, fontSize: 12, fontWeight: '600' }, error: { padding: 24 } });
