import { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '../../lib/supabase';
import { palette } from '../../lib/theme';
import { Button, Eyebrow, Field, Message, Page, Title } from '../../components/ui';

export default function CreateCircle() {
 const [title, setTitle] = useState(''); const [author, setAuthor] = useState(''); const [chapters, setChapters] = useState(''); const [description, setDescription] = useState(''); const [cover, setCover] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
 async function submit() { if (!supabase) { setError('Supabase is not configured.'); return; } const { data: { user } } = await supabase.auth.getUser(); if (!user) { router.push('/auth'); return; } if (!title.trim() || !author.trim() || Number(chapters) < 1) { setError('Add a book title, author, and a chapter count.'); return; } setBusy(true); setError(''); const { data, error: e } = await supabase.rpc('create_reading_session', { p_book_title: title.trim(), p_author: author.trim(), p_total_chapters: Number(chapters), p_description: description.trim() || null, p_cover_image_url: cover.trim() || null, p_start_date: null, p_target_end_date: null }); if (e || !data) setError(e?.message ?? 'The circle could not be created.'); else router.replace(`/sessions/${data}`); setBusy(false); }
 return <Page><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.back} onPress={() => router.back()}>‹  All reading circles</Text><Eyebrow>START A READING CIRCLE</Eyebrow><Title>Every good read{ '\n' }<Text style={s.italic}>starts somewhere.</Text></Title><Text style={s.copy}>Pick a book and invite people into the conversation.</Text><Text style={s.label}>Book title</Text><Field value={title} onChangeText={setTitle} placeholder="e.g. The Creative Act" maxLength={160} /><Text style={s.label}>Author</Text><Field value={author} onChangeText={setAuthor} placeholder="e.g. Rick Rubin" maxLength={120} /><Text style={s.label}>Total chapters</Text><Field value={chapters} onChangeText={setChapters} placeholder="e.g. 24" keyboardType="number-pad" /><Text style={s.label}>What should readers know? (optional)</Text><Field value={description} onChangeText={setDescription} placeholder="A note about this reading circle…" multiline maxLength={1000} style={{ minHeight: 92, textAlignVertical: 'top' }} /><Text style={s.label}>Cover image URL (optional)</Text><Field value={cover} onChangeText={setCover} placeholder="https://…" autoCapitalize="none" keyboardType="url" />{error ? <Message error>{error}</Message> : null}<Button title={busy ? 'Creating your circle…' : 'Create reading circle'} disabled={busy} onPress={() => void submit()} /><Text style={s.note}>All reading circles are public. You’ll be the first to join.</Text></ScrollView></KeyboardAvoidingView></Page>;
}
const s = StyleSheet.create({ content: { padding: 22, paddingTop: 24, paddingBottom: 40 }, back: { color: palette.sageDark, fontSize: 13, marginBottom: 28 }, italic: { color: palette.sage, fontStyle: 'italic' }, copy: { color: palette.muted, lineHeight: 21, marginBottom: 20 }, label: { color: palette.ink, fontSize: 12, fontWeight: '600' }, note: { color: '#92988f', textAlign: 'center', fontSize: 11, marginTop: 14 } });
