import { useEffect, useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, Text, Pressable, StyleSheet, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import * as Linking from 'expo-linking';
import { supabase } from '../../lib/supabase';
import { palette } from '../../lib/theme';
import { Button, Eyebrow, Field, Message, Page, Title } from '../../components/ui';

export default function AuthScreen() {
  const params = useLocalSearchParams<{ mode?: string }>(); const initial = params.mode === 'sign-up' ? 'sign-up' : 'sign-in';
  const [mode, setMode] = useState<'sign-in' | 'sign-up' | 'reset' | 'update-password'>(initial); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => {
    const client = supabase;
    if (!client) return;
    const { data } = client.auth.onAuthStateChange(event => { if (event === 'PASSWORD_RECOVERY') setMode('update-password'); });
    const handleUrl = async (url: string | null) => { if (!url) return; try { const parsed = new URL(url); const params = new URLSearchParams(parsed.hash.slice(1) || parsed.search.slice(1)); const recovery = params.get('type') === 'recovery'; if (recovery) setMode('update-password'); const code = parsed.searchParams.get('code'); if (code) { const { error: e } = await client.auth.exchangeCodeForSession(code); if (e) setError(e.message); else if (!recovery) router.replace('/(tabs)'); return; } const accessToken = params.get('access_token'); const refreshToken = params.get('refresh_token'); if (!accessToken || !refreshToken) return; const { error: e } = await client.auth.setSession({ access_token: accessToken, refresh_token: refreshToken }); if (e) setError(e.message); else if (!recovery) router.replace('/(tabs)'); } catch { setError('This sign-in link is invalid or expired. Request a new one and try again.'); } };
    const listener = Linking.addEventListener('url', event => { void handleUrl(event.url); });
    void Linking.getInitialURL().then(handleUrl);
    return () => { listener.remove(); data.subscription.unsubscribe(); };
  }, []);
  async function submit() { if (!supabase) { setError('Supabase is not configured. Add apps/mobile/.env to connect.'); return; } setBusy(true); setError(''); setNotice(''); if (mode === 'update-password') { const { error: e } = await supabase.auth.updateUser({ password }); if (e) setError(e.message); else { setNotice('Your password has been updated.'); setMode('sign-in'); } setBusy(false); return; } const result = mode === 'sign-up' ? await supabase.auth.signUp({ email: email.trim(), password, options: { data: { display_name: name.trim() }, emailRedirectTo: Linking.createURL('auth') } }) : await supabase.auth.signInWithPassword({ email: email.trim(), password }); if (result.error) setError(result.error.message); else if (mode === 'sign-up' && !result.data.session) setNotice('Check your email to confirm your account, then sign in.'); else router.replace('/(tabs)'); setBusy(false); }
  return <Page><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Pressable onPress={() => router.back()}><Text style={s.back}>‹  Back</Text></Pressable><Eyebrow>YOUR PLACE IN THE CIRCLE</Eyebrow><Title>{mode === 'sign-in' ? 'Welcome back.' : mode === 'reset' ? 'Find your way back.' : mode === 'update-password' ? 'A fresh start.' : 'Come read with us.'}</Title><Text style={s.copy}>A good book is even better when you share it.</Text>{mode === 'sign-up' && <><Text style={s.label}>Display name</Text><Field value={name} onChangeText={setName} placeholder="How readers will know you" maxLength={60} /></>}{mode !== 'update-password' && <><Text style={s.label}>Email</Text><Field value={email} onChangeText={setEmail} placeholder="you@example.com" keyboardType="email-address" autoCapitalize="none" autoComplete="email" /></>}{mode !== 'reset' && <><Text style={s.label}>{mode === 'update-password' ? 'New password' : 'Password'}</Text><Field value={password} onChangeText={setPassword} placeholder={mode === 'update-password' ? 'Choose a new password' : 'At least 8 characters'} secureTextEntry autoCapitalize="none" /></>}{mode === 'sign-in' && <Pressable onPress={() => { setMode('reset'); setNotice(''); setError(''); }}><Text style={s.link}>Forgot password?</Text></Pressable>}<Message error={Boolean(error)}>{error}</Message><Message>{notice}</Message><Button title={busy ? 'One moment…' : mode === 'reset' ? 'Send reset link' : mode === 'sign-in' ? 'Sign in' : mode === 'update-password' ? 'Update password' : 'Create account'} disabled={busy} onPress={async () => { if (mode !== 'reset') return submit(); if (!supabase) { setError('Supabase is not configured.'); return; } setBusy(true); const { error: e } = await supabase.auth.resetPasswordForEmail(email.trim(), { redirectTo: Linking.createURL('auth') }); setError(e?.message ?? ''); if (!e) setNotice('If an account exists, a password reset email is on its way. Open it on this device to choose a new password.'); setBusy(false); }} />{mode !== 'reset' && mode !== 'update-password' && <Pressable onPress={() => { setMode(mode === 'sign-in' ? 'sign-up' : 'sign-in'); setError(''); setNotice(''); }}><Text style={s.switch}>{mode === 'sign-in' ? 'New here? Create an account' : 'Already have an account? Sign in'}</Text></Pressable>}</ScrollView></KeyboardAvoidingView></Page>;
}
const s = StyleSheet.create({ content: { padding: 25, paddingTop: 35, flexGrow: 1 }, back: { color: palette.sageDark, fontSize: 14, marginBottom: 35 }, copy: { color: palette.muted, lineHeight: 21, marginBottom: 25 }, label: { color: palette.ink, fontSize: 12, fontWeight: '600' }, link: { color: palette.sageDark, textAlign: 'right', fontSize: 12, marginTop: -4, marginBottom: 12 }, switch: { color: palette.sageDark, fontSize: 13, textAlign: 'center', marginTop: 21 } });
