import type en from './en';
const ja: Record<keyof typeof en, string> = {
  'meta.title':'Books & Friends — もっと身近に読書を','meta.description':'次に読む本と、一緒に読書を楽しむ仲間を見つけましょう。',
  'language.label':'言語','language.english':'English','language.burmese':'မြန်မာ','language.japanese':'日本語',
  'nav.discover':'見つける','nav.how':'使い方','nav.start':'読書サークルを始める','nav.reading':'読書記録','nav.profile':'プロフィール設定','nav.notifications':'お知らせ','nav.signIn':'ログイン','nav.join':'サークルに参加','nav.signOut':'ログアウト','nav.signingOut':'ログアウト中…','nav.signOutError':'ログアウトできませんでした：',
  'home.eyebrow':'インターネットの、ほっとできる場所','home.titleA':'本との出会い。','home.titleB':'一緒ならもっと楽しい。','home.description':'語り合いたくなる本と、読書仲間を見つけましょう。自分のペースで読み、心に残ったことを共有できます。','home.cta':'次に読む本を見つける','home.note':'小さな読書サークル、大きな発見。','home.art':'物語を楽しむ余白を。','home.bookArt':'ゆっくり読むということ','home.footer':'読書に、もう少し豊かな意味を。',
  'discover.eyebrow':'次のページへ','discover.title':'読書サークル','discover.description':'読み進めている物語と、一緒に楽しむ仲間。','discover.all':'すべてのサークルを見る','discover.search':'本や著者を検索…','discover.searchLabel':'本と著者を検索','discover.live':'コミュニティから最新情報','discover.preview':'まずはおすすめのサークルから','discover.loading':'仲間を探しています…','discover.reading':'みんなで読書中','discover.readers':'読者 {count} 人','discover.first':'最初の参加者になる','discover.groupProgress':'みんなの進捗','discover.none':'サークルが見つかりません','discover.tryAgain':'別の本や著者で検索してみてください。','discover.demo':'Supabaseに接続されるまで、サンプルのサークルを表示します。','discover.howTitle':'読書は分かち合うともっと楽しい。','discover.howText':'サークルを作り、同じページを読み、会話が広がるのを楽しみましょう。','discover.joinNow':'今すぐ参加','discover.example1':'小さな驚きと科学、そして語り合いたいことがたくさん。','discover.example2':'友情、創造性、そして一緒に作る世界。','discover.example3':'ゆっくり読み、心に響くページに余白を残して。',
  'auth.back':'Books & Friendsに戻る','auth.signupEyebrow':'ここから素敵なことが始まります','auth.signinEyebrow':'おかえりなさい','auth.signupTitle':'さあ、こちらへ。','auth.signinTitle':'また会えてうれしいです。','auth.signupText':'本を楽しむ時間を大切にする読者の仲間になりましょう。','auth.signinText':'あなたの読書サークルが、ここで待っています。','auth.name':'お名前','auth.namePlaceholder':'お呼びするお名前','auth.email':'メールアドレス','auth.emailPlaceholder':'you@example.com','auth.password':'パスワード','auth.passwordNew':'new-password','auth.passwordCurrent':'current-password','auth.passwordPlaceholder':'8文字以上','auth.forgot':'パスワードをお忘れですか？','auth.loading':'処理中…','auth.create':'アカウントを作成','auth.submit':'ログイン','auth.confirm':'メールを確認してアカウントを認証後、ログインしてください。','auth.setup':'アカウントを作成するには、環境設定でSupabaseに接続してください。','auth.already':'すでにサークルのメンバーですか？','auth.new':'初めてですか？','auth.switchSignin':'ログイン','auth.switchSignup':'アカウントを作成',
  'forgot.eyebrow':'新しいスタートへ','forgot.title':'パスワードをお忘れですか？','forgot.text':'メールアドレスを入力すると、パスワード再設定リンクをお送りします。','forgot.submit':'再設定リンクを送信','forgot.sent':'アカウントが存在する場合、再設定リンクをメールでお送りします。','forgot.back':'ログインに戻る',
  'reset.title':'新しいパスワードを設定','reset.text':'安全で覚えやすいパスワードを設定してください。','reset.submit':'パスワードを更新','reset.success':'パスワードを更新しました。ログインできます。','reset.invalid':'再設定リンクが無効か、有効期限が切れています。新しいリンクを取得してください。',
  'circle.all':'すべての読書サークル','circle.preview':'サークルのプレビュー','circle.previewTitle':'この読書サークルはプレビューです。','circle.previewText':'実際のサークルに参加するには、Supabaseに接続してアカウントを作成してください。','circle.join':'Books & Friendsに参加','circle.eyebrow':'本を囲んで、仲間と読む','circle.by':'著者：{author}','circle.chapters':'全{count}章','circle.readers':'読者{count}人','circle.groupProgress':'みんなの進捗 {percent}%','circle.joinAction':'このサークルに参加','circle.joining':'参加中…','circle.progressEyebrow':'ページをめくるたび、一緒に','circle.progressTitle':'読者の進捗','circle.reader':'人','circle.readersPlural':'人','circle.you':'あなた','circle.noReaders':'まだ参加者はいません。','circle.yourReading':'あなたの読書','circle.keepPlace':'自分のペースで読み進めましょう。','circle.chapter':'章','circle.note':'メモ','circle.optionalThought':'ひとこと（任意）…','circle.saveProgress':'進捗を保存','circle.savedProgress':'進捗を保存しました。','circle.conversation':'みんなの会話','circle.readingNotes':'読書メモ','circle.notesCount':'メモ {count} 件','circle.quiet':'まだ静かなページです。最初のメモを残しましょう。','circle.commentPlaceholder':'読書中に感じたことを共有…','circle.chapterPlaceholder':'章','circle.postNote':'メモを投稿','circle.notePosted':'メモを投稿しました。','circle.signInReact':'ログインしてリアクション','circle.reactTitle':'{name}さんのコメントへのリアクション','circle.reactWith':'{emoji}でリアクション','circle.reacted':'{names}さんが{emoji}でリアクションしました','circle.yourReaction':'あなたのリアクション','circle.addReaction':'{emoji}でリアクション','circle.reactionCount':'{emoji} リアクション{count}件','circle.hostedBy':'{name}さんが主催する読書サークル。','circle.sharedRead':'本を分かち合い、語り合う仲間がいます。','circle.loading':'読書サークルを開いています…','circle.progressPrompt':'全{total}章中 {current}章',
  'create.eyebrow':'読書サークルを始める','create.titleA':'良い読書はいつも','create.titleB':'ここから始まる。','create.text':'本を選んで、語り合う仲間を招待しましょう。','create.book':'本のタイトル','create.bookExample':'例：The Creative Act','create.author':'著者','create.authorExample':'例：Rick Rubin','create.chapters':'総章数','create.chaptersExample':'例：24','create.description':'読者に伝えたいこと','create.descriptionPlaceholder':'この読書サークルについて…','create.cover':'表紙画像のURL','create.start':'開始日','create.end':'目標終了日','create.optional':'任意','create.submit':'読書サークルを作成','create.busy':'サークルを作成中…','create.footnote':'サークルは公開されます。あなたが最初の参加者です。','create.error':'サークルを作成できませんでした。もう一度お試しください。',
  'my.eyebrow':'あなたの読書ライフ','my.title':'読書記録','my.text':'参加しているサークルを一か所にまとめました。','my.emptyTitle':'次に読む本があなたを待っています。','my.emptyText':'サークルに参加して、一緒に読書を楽しみましょう。','my.explore':'サークルを探す','my.chapter':'全{total}章中 {current}章',
  'notifications.eyebrow':'サークルからのお知らせ','notifications.title':'お知らせ','notifications.markAll':'すべて既読にする','notifications.emptyTitle':'すべて確認しました。','notifications.emptyText':'サークルで何かあれば、ここにお知らせします。','notifications.comment':'{name}さんが「{book}」にメモを投稿しました。','notifications.reaction':'{name}さんが「{book}」の読書メモにリアクションしました。','notifications.member':'{name}さんが「{book}」に参加しました。','notifications.update':'「{book}」に更新があります。',
  'profile.back':'読書記録','profile.eyebrow':'サークルの中のあなたの場所','profile.title':'プロフィール設定','profile.intro':'顔が見えると、読書サークルがもっと身近になります。','profile.photo':'プロフィール写真','profile.photoTypes':'JPEG、PNG、WebP · 最大2MB','profile.changePhoto':'写真を変更','profile.uploadPhoto':'写真をアップロード','profile.removePhoto':'削除','profile.name':'表示名','profile.bio':'自己紹介','profile.bioPlaceholder':'好きな本について少し教えてください…','profile.save':'プロフィールを保存','profile.saving':'保存中…','profile.saved':'プロフィールを保存しました。','profile.photoSaved':'プロフィール写真を更新しました。','profile.photoRemoved':'プロフィール写真を削除しました。','profile.choosePhoto':'JPEG、PNG、またはWebP画像を選んでください。','profile.photoTooLarge':'2MB未満の画像を選んでください。','profile.signinText':'ログインして読書記録をつけ、サークルをフォローし、会話に参加しましょう。','profile.createAccount':'アカウントを作成','profile.account':'アカウント','profile.photoRemoveConfirm':'プロフィール写真を削除しますか？','profile.photoRemoveText':'プロフィールから写真を削除します。','profile.cancel':'キャンセル','profile.remove':'写真を削除','profile.nameRequired':'表示名を入力してください。','profile.photoCleanup':'プロフィール写真を更新しましたが、以前の画像を削除できませんでした。','profile.photoDeleteFailure':'プロフィール写真を削除しましたが、保存された画像を削除できませんでした。',
};
export default ja;
